lewagon/dotfiles

zshrc

Had to do a reinstall of a student's laptop after their keyboard stopped working (failed ubuntu update). Previous setup didn't work until I changed the ~ to $HOME on line 17

Changed the ~ sign to $HOME

---

install.sh

No need to symlink these files in home directory, their purpose is to be symlinked in Sublime Text directories.

skip symlinking of *.sublime-settings files in home directory

---

Package Control.sublime-settings

Seems like all students have an error message about this plugin that can't be found.
Let's remove it to avoid too many tickets about that during setup days 👌

remove A File Icon

---

zshrc

this restores the `gst`, `gcm` etc plugins ping @ssaunier 👌

add git plugin to restore gitfast aliases

---

Package Control.sublime-settings

More and more student is having unnecessary error for not closing their brackets, this additional package can help them to notice them easily

add `BracketHighlighter` as default setup pack

---

zshrc

the old homebrew analytics url is 404

Update zshrc comment

---

zshrc

This PR updates [the loading instructions](https://github.com/nvm-sh/nvm#install--update-script) of `nvm` add [this script](https://github.com/lewagon/setup/pull/215) to execute `nvm use` automatically when a `.nvmrc` file is present in the current folder of the shell to have the same behavior than `rbenv`. 
It should be merged with https://github.com/lewagon/setup/pull/215 and https://github.com/lewagon/karr/pull/665

update nvm load

---

zshrc

this disables the virtualenv auto-loading as we are going to use `pyenv global` and `pyenv local` command to switch virtualenvs from a project to another. @barangerbenjamin @gmanchon please review. To be merged with https://github.com/lewagon/data-setup/pull/40

remove virtualenv auto-loading

---

gitconfig

Students experience a warning message when trying to pull from git, during AirBnB / Project.
This message is new to Git version 2.27.0, and this PR is just a way to enforce the previous git behaviour.

Add default pull reconciliation strategy for git

---

Package Control.sublime-settings

this fixes https://github.com/lewagon/data-setup/issues/23 @ssaunier please review

add flake8 linter and AutoPEP8 formatter

---

install.sh

This should fix the installation of the [zsh syntax highlighting](https://github.com/zsh-users/zsh-syntax-highlighting)

git clone zsh autosuggestions

---

Package Control.sublime-settings
zshrc

Students think they are missing some packages because they are not sorted alphabetically, like Sublime does. 
This PR sorts the package list. 
Other point I'm thinking about: 
Some of these packages are useful for web only, others are useful for data only. 
Shouldn't we have two version of this package list, one for each program? Just like we have two different setups. 
Or even two dotfiles versions since some other part of them are differing. For data, they don't need nvm, the tab size should be 4... 
What is your thought about this @ssaunier ?

sort sublime package list

---

zshrc

Fix https://teamwagon.slack.com/archives/CPRHU0397/p1615076768006400
And https://lewagon-alumni.slack.com/archives/C015E0C601F/p1615166762127300
If `nvm` is not installed (web dev students not there yet in the setup, or data students), the `load-nvmrc` function is not going to be executed.

Don't load nvm function if nvm is not installed

---

settings.json

These options were messing with the editor UX, triggering unwanted behaviour... etc.
Removing them makes the experience way smoother, and keep the linting hints.

Remove Ruby extension settings messing with the editor

---

profile

this PR adds a `~/.profile` file to the setup in order to handle the PATH manipulations for pyenv
pyenv 2.0.0 introduced around May 2021 a [breaking change](https://github.com/pyenv/pyenv/blob/master/CHANGELOG.md) where the PATH is [no longer handled](https://github.com/pyenv/pyenv/issues/1649#issuecomment-694388530) by the `pyenv init`command
the solution proposed when running the `pyenv init` command is to handle the PATH for pyenv manually in the `~/.profile` file (where the user custom PATH manipulations are supposed to take place, not in the `~/.zshrc` file) :
``` bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

[pyenv] handle the PATH for pyenv

---

git_setup.sh

This will make git_setup.sh less likely to break in a confusing way should untoward input be provided.

Add quoting to improve robustness

---

settings.json

Two things have been changed
- I've added python specific settings
- I've removed settings that were duplicating default VScode values
One problem remains: if we split the setting into two as I did, students will be confused when jumping from one language to another. Let's have a chat about why did we add so many new constrains beyond defaut VScode behavior. e.g.
- The default 17pt value for font size is so huge! Why?
- Why "editor.formatOnPaste:true"
- Why changed "editor.multiCursorModifier" default settings?
- ...
and see if we can find middle grouds that minimizes differences between python and ruby/default student settings

add python specific vscode settings

---

zshrc

This set `ipdb` as the default Python debugger cf https://github.com/lewagon/data-solutions/pull/878

use ipdb as the default Python debugger

---

settings.json

- Add default Github light theme to VScode. It's the one we recommend our teacher to use when they get filmed ([see notion](https://www.notion.so/lewagon/Lecture-video-recording-guidelines-fb2fd65863fa432399fc1a6e44305b3b#da77d412564147dd92075652471f05ff)). I hope you're OK with it in web dev too? Because currently, the default VScode purple theme is pretty horrible !!
[Linked PR in setup](https://github.com/lewagon/setup/compare/vscode-setup?expand=1)
- Add `"workbench.editor.enablePreview": true,` to mimic sublime behavior 😍 
- Add python-specific behaviors

update vscode setup

---

zshrc

It seems that we don't need the [`pyenv` plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pyenv) which is causing troubles lately with some hints at `~/.zprofile` / `~/.profile`.
We have other lines in the configuration which already run the `pyenv init`. The plugin was just provided with the BASH function `pyenv_prompt_info` that can be easily replaced.
It works on my laptop, but to be extra sure, could you:
Thank you all 🙏

Remove pyenv plugin

---

gitconfig

Fix https://github.com/lewagon/dotfiles/issues/119

Make git aliases agnostic of git default branch name

---

settings.json

This is needed for data-engineering-bootcamp where students will create their venv inside each challenge folder using `poetry install`
- We don't want to pollute their search
- But we don't want to hide the folder .venv altogether, it's better to see that it exists to understand what's happening

vs code remove .venv folder from search
